language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
    global:
        - RUST_BACKTRACE=1
script:
  - cd bootstrap
  - cargo build
  - cargo test
