load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "air_runtime",
    srcs = ["air_runtime.c"],
    hdrs = ["air_runtime.h"],
)

# Expose the library output for copying
filegroup(
    name = "libair_runtime.a",
    srcs = [":air_runtime"],
    output_group = "archive",
)
