load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library")

rust_library(
    name = "airc-syntax",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [":pest-files"],
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//compiler:__subpackages__"],
    deps = all_crate_deps(normal = True),
)

filegroup(
    name = "pest-files",
    srcs = glob(["src/**/*.pest"]),
)
