// Part of the Aero programming language. License: MIT.

//! Wrapper for Rust's `f32` utilities for use in Aero's `f32`.

#[macro_use]
extern crate aero_core;
#[macro_use]
extern crate rustler;

aero_export! {
  "aero_core_f32",
  [
    (add,     ::std::ops::Add::add, (f32, f32), f32),
    (sub,     ::std::ops::Sub::sub, (f32, f32), f32),
    (mul,     ::std::ops::Mul::mul, (f32, f32), f32),
    (div,     ::std::ops::Div::div, (f32, f32), f32),
    (rem,     ::std::ops::Rem::rem, (f32, f32), f32),
    (floor,   f32::floor,      (f32),           f32),
    (ceil,    f32::ceil,       (f32),           f32),
    (round,   f32::round,      (f32),           f32),
    (trunc,   f32::trunc,      (f32),           f32),
    (fract,   f32::fract,      (f32),           f32),
    (abs,     f32::abs,        (f32),           f32),
    (mul_add, f32::mul_add,    (f32, f32, f32), f32),
    (powi,    f32::powi,       (f32, i32),      f32),
    (powf,    f32::powf,       (f32, f32),      f32),
    (inv,     f32::recip,      (f32),           f32),
    (sqrt,    f32::sqrt,       (f32),           f32),
    (cbrt,    f32::cbrt,       (f32),           f32),
    (exp,     f32::exp,        (f32),           f32),
    (exp2,    f32::exp2,       (f32),           f32),
    (exp_m1,  f32::exp_m1,     (f32),           f32),
    (ln,      f32::ln,         (f32),           f32),
    (log,     f32::log,        (f32, f32),      f32),
    (log2,    f32::log2,       (f32),           f32),
    (log10,   f32::log10,      (f32),           f32),
    (ln_1p,   f32::ln_1p,      (f32),           f32),
    (hypot,   f32::hypot,      (f32, f32),      f32),
    (sin,     f32::sin,        (f32),           f32),
    (cos,     f32::cos,        (f32),           f32),
    (tan,     f32::tan,        (f32),           f32),
    (asin,    f32::asin,       (f32),           f32),
    (acos,    f32::acos,       (f32),           f32),
    (atan,    f32::atan,       (f32),           f32),
    (atan2,   f32::atan2,      (f32, f32),      f32),
    (sinh,    f32::sinh,       (f32),           f32),
    (cosh,    f32::cosh,       (f32),           f32),
    (tanh,    f32::tanh,       (f32),           f32),
    (asinh,   f32::asinh,      (f32),           f32),
    (acosh,   f32::acosh,      (f32),           f32),
    (atanh,   f32::atanh,      (f32),           f32),
    (to_deg,  f32::to_degrees, (f32),           f32),
    (to_rad,  f32::to_radians, (f32),           f32)
  ],
  [
    ("add",     2, add),
    ("sub",     2, sub),
    ("mul",     2, mul),
    ("div",     2, div),
    ("rem",     2, rem),
    ("floor",   1, floor),
    ("ceil",    1, ceil),
    ("round",   1, round),
    ("trunc",   1, trunc),
    ("fract",   1, fract),
    ("abs",     1, abs),
    ("mul_add", 3, mul_add),
    ("powi",    2, powi),
    ("powf",    2, powf),
    ("inv",     1, inv),
    ("sqrt",    1, sqrt),
    ("cbrt",    1, cbrt),
    ("exp",     1, exp),
    ("exp2",    1, exp2),
    ("exp_m1",  1, exp_m1),
    ("ln",      1, ln),
    ("log",     2, log),
    ("log2",    1, log2),
    ("log10",   1, log10),
    ("ln_1p",   1, ln_1p),
    ("hypot",   2, hypot),
    ("sin",     1, sin),
    ("cos",     1, cos),
    ("tan",     1, tan),
    ("asin",    1, asin),
    ("acos",    1, acos),
    ("atan",    1, atan),
    ("atan2",   2, atan2),
    ("sinh",    1, sinh),
    ("cosh",    1, cosh),
    ("tanh",    1, tanh),
    ("asinh",   1, asinh),
    ("acosh",   1, acosh),
    ("atanh",   1, atanh),
    ("to_deg",  1, to_deg),
    ("to_rad",  1, to_rad)
  ]
}
