name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
      - run: rebar3 fetch
      - run: rebar3 do build, check
      - run: rebar3 test
